# nixpacks.toml for React + Vite + Bun + SPA

# Force Node
providers = ['node']

[variables]
# Build process variables
NIXPACKS_NODE_VERSION = "20"
NIXPACKS_BUN_VERSION = "latest"
# SPA mode with Caddy fallback
NIXPACKS_SPA_CADDY = "true"
# Build env variables
NODE_ENV = "staging"

[phases.setup]
# Install bun and dependencies
nixPkgs = ['nodejs', 'bun']

[phases.install]
# Forcing Bun
cmds = [
  'bun install --frozen-lockfile'
]

[phases.build]
# Forcing Bun
cmds = [
  'bun run build'
]

[start]
# Caddy serving SPA fallback
# Coolify detects SPA and sets Caddy up
cmd = 'caddy file-server --root dist --listen :$PORT --browse'